"""empty message

Revision ID: 1a0868581956
Revises: 564c2288a2fc
Create Date: 2020-11-17 23:04:07.238464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a0868581956'
down_revision = '564c2288a2fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_fk',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_fk',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
