"""empty message

Revision ID: 7b8686fbf175
Revises: 31539f427a43
Create Date: 2020-11-16 04:34:27.302149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b8686fbf175'
down_revision = '31539f427a43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    op.execute('update todos set completed= False where completed is NULL;');
    op.alter_column('todos', 'completed', nullable = False);

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
