"""empty message

Revision ID: a5de7fe53ae9
Revises: 1a0868581956
Create Date: 2020-11-18 19:55:57.364881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5de7fe53ae9'
down_revision = '1a0868581956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('todos_list_fk_fkey', 'todos', type_='foreignkey')
    op.create_foreign_key(None, 'todos', 'todo_list', ['list_fk'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.create_foreign_key('todos_list_fk_fkey', 'todos', 'todo_list', ['list_fk'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
